# Generated by Django 2.1.1 on 2018-09-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorprofile', '0003_auto_20180919_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
