# Generated by Django 2.1.1 on 2018-09-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_tag_posts'),
        ('post', '0003_auto_20180922_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='search.Tag'),
        ),
    ]
